### ISSUE TITLE
Support job triggering based on provided z-stream (stable, rc, nightly, etc..)

### ISSUE THREAD

**Issue by chetna14manku** [RedHatQE/ci-jobs-trigger#109]
z-stream.py triggers job when there is new stable build only. It should also support job-triggers when stream is candidate or other than stable.
We can update [config](https://github.com/RedHatQE/ci-jobs-trigger/blob/main/config-examples/zstream-trigger-config.example.yaml) to have one more key for specifying z-stream and it to query versions.

```
versions:
  "4.13":
     <z-stream>:
          - <openshift-ci-test-name-1>
          - <openshift-ci-test-name-2>
```

**Comment by rnetser** [comment]
@chetna14manku can this be closed?

**Comment by chetna14manku** [comment]
Closing this issue for now
