### ISSUE TITLE
Add support for trigger at desired cadence

### ISSUE THREAD

**Issue by Simranpal** [RedHatQE/ci-jobs-trigger#115]
Specifically for zstream, right now we plan to trigger once a month. We may increase the cadence in future. 
We should have the option to specify the cadence in the config so it can be adjustable.

The stable releases for z-stream version happen typically once a week, unless it gets delayed or gets skipped for that week due to upcoming downtime. 
The tool can check for new versions on first Monday of every month to get the latest version so far.  Is is possible to do that currently?
Thanks

**Comment by rnetser** [comment]
code was merged; you can now add `cron_schedule` to the z-stream config
