### ISSUE TITLE
WIP: Add z-stream support to trigger jobs for rosa versions - 185

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/ci-jobs-trigger#186]
[Auto generated]
Number: [#185]

**Comment by msi-b1** [comment]
[38;5;21mci-jobs-trigger[0m[pull_request][7695-11ef-9885-d027f7314a27][PR 185]: Closing issue for PR: Update z-stream to trigger jobs for rosa versions.
PR was closed.
