### ISSUE TITLE
zstream-trigger fails to process already_processed_version at times.

### ISSUE THREAD

**Issue by smatula** [RedHatQE/ci-jobs-trigger#94]
zstream-trigger.py function already_processed_version() uses subscript [0] to check against new version.  When updating version  no ordering is performed. Latest version may or may not be in subscript [0] of list.  This can lead to running multiple  times for the same version.

Could either update check to make sure new version is <= every version in list.

or 

enhance update_processed_version() to sort list

from packaging.version import Version
processed_versions_file_content[base_version] = sorted(list(set(processed_versions_file_content[base_version])), key=Version, reverse=True)

**Comment by myakove** [comment]
fixed in https://github.com/RedHatQE/ci-jobs-trigger/commit/08ce291f3c8244e83f23662d1ce3b1d8842a3616

**Comment by smatula** [comment]
@myakove Hi current already processed file after a run and update yesterday is the following:
{"4.14": ["4.14.19", "4.14.21", "4.14.20"], "4.15": ["4.15.9", "4.15.8", "4.15.7"]}
The sort should be performed after set.  set() is unordered and the order of the elements is not guaranteed to be preserved.

**Comment by myakove** [comment]
You are more than welcome to open PR to fix this.
